
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar"; // Navbar ইম্পোর্ট
import Footer from "@/components/Footer"; // Footer ইম্পোর্ট


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* এখানে Navbar বসানো হলো */}
        <Navbar /> 
                {/* এখানে Navbar বসানো হলো */}
        <Footer /> 
        
        {/* এই চিলড্রেন হলো বাকি সব পেজের কন্টেন্ট */}
        {children}
      </body>
    </html>
  );

}